name: Build and Deploy Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push container
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: 'ky'
          resourceGroup: 'Kaimai-Yoti-2'
          targetPort: 8080
          ingress: 'external'
          environmentVariables: |
            NODE_ENV=production
            PORT=8080
            YOTI_CLIENT_SDK_ID=${{ secrets.YOTI_CLIENT_SDK_ID }}
            APP_URL=${{ secrets.APP_URL }}
            YOTI_KEY_FILE_PATH=/app/keys/Kaimai-Yoti-ultra-basic-share-keys.pem
